site_name: Pinax Stripe
pages:
- Home: index.md
- Reference:
    - Settings: reference/settings.md
    - Signals: reference/signals.md
    - Template Tags: reference/templatetags.md
    - URLs: reference/urls.md
    - Utilities: reference/utils.md
    - Views: reference/views.md
    - Webhooks: reference/webhooks.md
- About:
    - License: about/license.md
    - History: about/history.md
    - Release Notes: about/release-notes.md
theme: readthedocs
markdown_extensions:
    - admonition
